# Generated by Django 3.0.7 on 2020-06-25 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_num', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('visa_type', models.CharField(choices=[('student_visa', 'Student visa'), ('tourist_visa', 'Tourist visa'), ('work_visa', 'Work visa'), ('business_visa', 'Business visa'), ('guest_visa', 'Guest visa'), ('pr_visa', 'PR visa')], default='student_visa', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('docs', models.FileField(upload_to='pdf-docs/')),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('answer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50)),
                ('full_username', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_num', models.CharField(blank=True, max_length=20, null=True)),
                ('step', models.CharField(choices=[('main_menu', 'Main page'), ('faqs', 'FAQs'), ('about', 'About'), ('countries_list', 'Counties List'), ('application_name', 'Application Name'), ('application_contact', 'Application Contact'), ('application_visa_type', 'Application visa type')], default='main_menu', max_length=255)),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
